---
# MoM must come up first to provide configuration for everything else
vms:
  - name: mom.vm
    box: puppetlabs/centos-7.2-64-nocm
    roles:
      - pe-forward-console
      - pe-memory-tuning2
      - pe-mom
      - el-stop-firewall
      - el-fix-path
      - 2gb-memory
      - base

  - name: pdb1.vm
    box: puppetlabs/centos-7.2-64-nocm
    roles:
      - pe-pdb
      - el-stop-firewall
      - el-fix-path
      - base

  - name: pdb2.vm
    box: puppetlabs/centos-7.2-64-nocm
    roles:
      - pe-pdb
      - el-stop-firewall
      - el-fix-path
      - base

  - name: compile1.vm
    box: puppetlabs/centos-7.2-64-nocm
    roles:
      - pe-memory-tuning2
      - pe-compile
      - el-stop-firewall
      - el-fix-path
      - 1gb-memory
      - base

# HAProxy must come up last for our DNS hacks
# The order of this system doesn't actually matter if you know IPs ahead of time
  - name: haproxy.vm
    box: puppetlabs/centos-7.2-64-nocm
    roles:
      - haproxy
      - el-stop-firewall
      - el-fix-path
      - base

  - name: agent.vm
    box: puppetlabs/centos-7.2-64-nocm
    roles:
      - el-stop-firewall
      - el-fix-path
      - base
      - agent

# vim: set ft=yaml:
